import { WeatherCodes } from '.';

// icons from http://erikflowers.github.io/weather-icons/
export const WeatherIcons = {
    [WeatherCodes.Tornado]: 'wi-tornado',
    [WeatherCodes.TropicalStorm]: 'wi-storm-showers',
    [WeatherCodes.Hurricane]: 'wi-hurricane',
    [WeatherCodes.SevereThunderstorms]: 'wi-storm-showers',
    [WeatherCodes.Thunderstorms]: 'wi-storm-showers',
    [WeatherCodes.MixedRainSnow]: 'wi-rain-mix',
    [WeatherCodes.MixedRainSleet]: 'wi-rain-mix',
    [WeatherCodes.MixedSnowSleet]: 'wi-rain-mix',
    [WeatherCodes.FreezingDrizzle]: 'wi-rain-mix',
    [WeatherCodes.Drizzle]: 'wi-sprinkle',
    [WeatherCodes.FreezingRain]: 'wi-rain-mix',
    [WeatherCodes.ShowersNight]: 'wi-night-showers',
    [WeatherCodes.ShowersDay]: 'wi-day-showers',
    [WeatherCodes.SnowFlurries]: 'wi-day-snow',
    [WeatherCodes.LightSnowShowers]: 'wi-day-snow',
    [WeatherCodes.BlowingSnow]: 'wi-day-snow-wind',
    [WeatherCodes.Snow]: 'wi-snow',
    [WeatherCodes.Hail]: 'wi-day-hail',
    [WeatherCodes.Sleet]: 'wi-day-sleet',
    [WeatherCodes.Dust]: 'wi-dust',
    [WeatherCodes.Foggy]: 'wi-day-haze',
    [WeatherCodes.Haze]: 'wi-day-haze',
    [WeatherCodes.Smoky]: 'wi-day-haze',
    [WeatherCodes.Blustery]: 'wi-day-windy',
    [WeatherCodes.Windy]: 'wi-day-windy',
    [WeatherCodes.Cold]: '',
    [WeatherCodes.Cloudy]: 'wi-cloudy',
    [WeatherCodes.MostlyCloudyNight]: 'wi-night-cloudy',
    [WeatherCodes.MostlyCloudyDay]: 'wi-day-cloudy',
    [WeatherCodes.PartlyCloudyNight]: 'wi-cloud',
    [WeatherCodes.PartlyCloudyDay]: 'wi-cloud',
    [WeatherCodes.ClearNight]: 'wi-night-clear',
    [WeatherCodes.Sunny]: 'wi-day-sunny',
    [WeatherCodes.FairNight]: 'wi-night-clear',
    [WeatherCodes.FairDay]: 'wi-day-sunny',
    [WeatherCodes.MixedRainAndHail]: 'wi-rain-mix',
    [WeatherCodes.Hot]: 'wi-hot',
    [WeatherCodes.IsolatedThunderstorms]: 'wi-thunderstorm',
    [WeatherCodes.ScatteredThunderstormsNight]: 'wi-night-thunderstorm',
    [WeatherCodes.ScatteredThunderstormsDay]: 'wi-day-thunderstorm',
    [WeatherCodes.ScatteredShowers]: 'wi-showers',
    [WeatherCodes.HeavySnowNight]: 'wi-night-snow',
    [WeatherCodes.ScatteredSnowShowers]: 'wi-night-snow',
    [WeatherCodes.HeavySnowDay]: 'wi-day-snow',
    [WeatherCodes.PartlyCloudy]: 'wi-cloud',
    [WeatherCodes.Thundershowers]: 'wi-thunderstorm',
    [WeatherCodes.SnowShowers]: 'wi-rain-mix',
    [WeatherCodes.IsolatedThundershowers]: 'wi-thunderstorm',
    [WeatherCodes.NotAvailable]: 'wi-alien',
};