trigger: none
pr: none 

pool:
  name: Hosted Ubuntu 1604

steps:
- task: Docker@2
  inputs:    
    containerRegistry: 'DockerHubXabaril'
    repository: 'xabarilcoding/esquioui'
    command: 'buildAndPush'
    Dockerfile: 'demos/AppWithUI/ui-dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest